# Generated by Django 4.2.6 on 2023-10-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="amount",
            field=models.FloatField(default=0.0),
        ),
    ]
