# Generated by Django 4.2.6 on 2023-11-01 02:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0003_alter_transaction_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="amount",
            new_name="balance",
        ),
    ]
