# Generated by Django 4.2.6 on 2023-11-01 05:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0004_rename_amount_account_balance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="receiver",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="sender",
        ),
    ]
