# Generated by Django 4.2.6 on 2023-11-02 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0005_remove_transaction_receiver_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="category",
        ),
        migrations.CreateModel(
            name="Categorization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=20)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transaction_category",
                        to="bank.transaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_transactions_category",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
