# Generated by Django 4.2.7 on 2023-11-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0007_alter_account_user_alter_categorization_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="selftransaction",
            field=models.BooleanField(default=False),
        ),
    ]
