# Generated by Django 4.2.7 on 2023-11-23 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0008_transaction_selftransaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorization",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction_category",
                to="bank.transaction",
            ),
        ),
    ]
