# Generated by Django 4.2.7 on 2023-11-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0009_alter_categorization_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="type",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
