# Generated by Django 4.2.7 on 2023-11-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0010_alter_account_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="type",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
