# Generated by Django 4.2.7 on 2023-11-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0011_alter_account_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="digits",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
