# Generated by Django 4.2.7 on 2023-11-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0012_account_digits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="digits",
            field=models.CharField(blank=True, default="0000", max_length=4, null=True),
        ),
    ]
